spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/skilllink_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

skilllink:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"

jwt:
  secret: ${JWT_SECRET:CHANGE_ME_SECRET_KEY}      # Get from env vars
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}