spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 0  # Random port for tests

spring.h2.console:
  enabled: true

logging:
  level:
    root: WARN
    org.springframework: INFO
    com.skilllink: DEBUG

jwt:
  secret: test_jwt_secret
  expiration: 3600000
  refresh-token:
    expiration: 604800000