server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: SkillLink-Backend
    # To set enviorments profile (dev, prod and test)
  profiles:

    active: ${SPRING_PROFILES_ACTIVE:dev}


  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/skilllinkdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

skilllink:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}

jwt:
  secret: ${JWT_SECRET:my_local_dev_secret}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}
